CREATE PROCEDURE ACTUALIZAR_USUARIO(
@IDUSUARIO INT =NULL,
@CONTRASENA VARCHAR(100) =NULL
)AS
BEGIN 

UPDATE Soluciones_Desarrollo.dbo.Usuario
SET Contrasena = ENCRYPTBYPASSPHRASE('password', @CONTRASENA)
WHERE IdUsuario = @IDUSUARIO
END