
CREATE PROCEDURE REGISTRA_USUARIO(
@NOMBRE VARCHAR(100) =NULL,
@APELLIDO VARCHAR(100) =NULL,
@USUARIO VARCHAR(100) =NULL,
@CONTRASENA VARCHAR(100) =NULL
)AS
BEGIN 
INSERT INTO Soluciones_Desarrollo.dbo.Usuario(Nombre,Apellidos,Usuario,Contrasena)VALUES(@NOMBRE,@APELLIDO,@USUARIO,ENCRYPTBYPASSPHRASE('password', @CONTRASENA));

END


